# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /archives/:year/:month/:day/:title/
relative_permalinks: true

# Additional settings
excerpt_separator: <!--more-->
comments: true
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Setup

title:            Keywords
tagline:          'Better than yelling at the TV'
description:      'The personal blog of <a href="http://kerim.oxus.net/">P. Kerim Friedman 傅可恩</a>. For his academic blogging please visit <a href="http://savageminds.org/">Savage Minds</a>.<br/><br/><a href="https://twitter.com/@kerim" target="_blank"><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://facebook.com/kerimfriedman" target="_blank"><i class="fa fa-facebook"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://plus.google.com/+KerimFriedman/about" target="_blank"><i class="fa fa-google-plus"></i></a>&nbsp;&nbsp;&nbsp;<a href="https://www.flickr.com/photos/kerim/" target="_blank" target="_blank"><i class="fa fa-flickr"></i></a>'
url:              http://kerim.github.io/
baseurl:          /keywords

author:
  name:           'Kerim Friedman'
  url:            https://twitter.com/kerim
  email: 'kerim.mail@oxus.net'

paginate:         15

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Prose 
prose:
  rooturl: '_posts'
  siteurl: 'http://keywords.oxus.net/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "post"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "academic"
              value: "academic"
            - name: "announcements"
              value: "announcements"
            - name: "culture"
              value: "culture"
            - name: "education"
              value: "education"
            - name: "gender"
              value: "gender"
            - name: "health"
              value: "health"
            - name: "images"
              value: "images"
            - name: "india"
              value: "india"
            - name: "info-tech"
              value: "info-tech"
            - name: "invited"
              value: "invited"
            - name: "juno"
              value: "juno"
            - name: "labor"
              value: "labor"
            - name: "language"
              value: "language"
            - name: "law"
              value: "law"
            - name: "links"
              value: "links"
            - name: "notable"
              value: "notable"
            - name: "politics"
              value: "politics"
            - name: "race"
              value: "race"
            - name: "taiwan"
              value: "taiwan"
            - name: "the-economy"
              value: "the-economy"
            - name: "the-environment"
              value: "the-environment"
            - name: "blog-post"
              value: "blog-post"
