# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup

title:            Kewywords
tagline:          'Better than yelling at the TV'
description:      'The personal blog of P. Kerim Friedman'
url:              http://kerim.oxus.net
baseurl:          /keywords/

author:
  name:           'Kerim Friedman'
  url:            https://twitter.com/kerim

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
