# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /archives/:year/:month/:day/:title/
relative_permalinks: false

# Setup

title:            Keywords
tagline:          'Better than yelling at the TV'
description:      'The personal blog of <a href"http://kerim.oxus.net/">P. Kerim Friedman 傅可恩</a>'
url:              http://kerim.oxus.net
baseurl:          /keywords/

author:
  name:           'Kerim Friedman'
  url:            https://twitter.com/kerim

paginate:         15

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
